# Generated by Django 3.0.7 on 2020-11-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userName',
            new_name='username',
        ),
    ]
